### ISSUE TITLE
ISO File based sshd is unusable at the moment

### ISSUE THREAD

**Issue by khorsmann** [adubovikov/sbcOS#8]
I must type this from the virtualbox console:

PAM _pam_load_conf_file: unable to open /etc/pam.d/common-auth
PAM _pam_init_handlers: error reading /etc/pam.d/sshd

So sshd process is restarting during monit and its not usable - also not with ssh localhost.

And for the archive - building machine:
```
vagrant box ubuntu/bionic64

root@sbcbuilder:~/sbcOS/ISO# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by adubovikov** [comment]
in the pam.d I have these files:
```
/rootfs/etc/pam.d# ls -l
total 12
-rw-r--r-- 1 root root  100 Jan 11  2017 monit
-rw-r--r-- 1 root root  520 May 27  2017 other
-rw-r--r-- 1 root root 2133 Mar  1 17:19 sshd

```

Do you have the same ?

**Comment by khorsmann** [comment]
Yes. I right build the sbc-public.sb file at this moment.

```
root@sbcbuilder:~/sbcOS# mkdir -p /mnt/dir; mount /root/sbcOS/SbcOS/build/img/sbc-public.sb /mnt/dir -t squashfs -o loop
root@sbcbuilder:~/sbcOS# cd /mnt/dir/
root@sbcbuilder:/mnt/dir# ls
bin  dev  etc  init  lib  lib64  linuxrc  mnt  proc  root  run  sbin  sys  tmp  usr  var
root@sbcbuilder:/mnt/dir# ls etc/
adjtime                 firewall.conf           inittab                 libaudit.conf           ntp.conf                redis/                  services                timezone
bash.bashrc             gai.conf                iproute2/               master/                 pam.conf                rpc                     shadow                  ucf.conf
bindresvport.blacklist  group                   issue                   modprobe.conf           pam.d/                  rsyslog.conf            skel/                   udev/
ca-certificates/        gshadow                 joe/                    monit/                  passwd                  rtpengine/              ssh/                    vdpau_wrapper.cfg
default/                hostname                kamailio/               motd                    profile                 scripts/                ssl/
dhcp/                   hosts                   ld.so.conf              nagios/                 protocols               security/               telegraf/
dhcpinterface           init.d/                 ld.so.conf.d/           network/                rc.d/                   selinux/                terminfo/
root@sbcbuilder:/mnt/dir# ls etc/pam.
pam.conf  pam.d/
root@sbcbuilder:/mnt/dir# ls etc/pam.d/
monit  other  sshd
```

**Comment by adubovikov** [comment]
let me add common-auth. It will help do local auth

**Comment by khorsmann** [comment]
I dont get the point where the etc/pam.d/* stuff hits the floor. Must be at the base-extracting of the deb-files i asume.

**Comment by adubovikov** [comment]
UsePAM no in the sshd_config
a patch is comming

**Comment by khorsmann** [comment]
With the below settings it works - which is realy unsecure for the weak password. Btw. the "default ssh-host-key" and "default /root/.ssh/*keys" seem also an security issue maybe.


```
UsePAM no
PermitRootLogin yes
```

**Comment by adubovikov** [comment]
so, just updated the scripts and config. About non secure - internaly we use public key and access to the system over ssh is only on the manager interface and from NOC's network - it gives enough security

**Comment by adubovikov** [comment]
in the scripts I have disabled copy authorized_keys with comments "Make an own key", but for now I have reanabled.

**Comment by khorsmann** [comment]
Its more an documentation problem i think - i saw the config/folder holds all the stuff. And for "first look and feel" an ISO was very convenient.

**Comment by adubovikov** [comment]
therefore just updated the image files as well :-) It uses now internal auth and public key

**Comment by khorsmann** [comment]
I will rebuild and report.

**Comment by khorsmann** [comment]
ssh into the box works now like a charme (of course if add an iptables rule)
